package io.github.ousatov.tools.memgraph;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Installs managed Memgraph agent instructions into a local instruction file.
 *
 * @author Oleksii Usatov
 */
final class AgentInstructionsInstaller {

  private static final String CODE_TEMPLATE = "AI-memgraph-code-template.md";
  private static final String MEMORY_TEMPLATE = "AI-memgraph-memory-template.md";
  private static final String PROJECT_TOKEN = "{{PROJECT_NAME}}";
  private static final String START_MARKER = "<!-- memgraph-ingester:start -->";
  private static final String END_MARKER = "<!-- memgraph-ingester:end -->";
  private static final String GENERATED_NOTICE =
      "<!-- Generated by memgraph-ingester. Re-run the executable to update this block. -->";
  private static final Pattern LEGACY_TEMPLATE_BLOCK =
      Pattern.compile(
          "(?ms)^## Knowledge Graph\\R\\R"
              + "Repo is indexed in Memgraph as \\*\\*`[^`]+`\\*\\*\\. Every query MUST include\\R"
              + "`project: '[^']+'`\\.\\R.*?"
              + "^> Memory is not logs\\. Store only what improves future decisions\\.\\R?");

  private AgentInstructionsInstaller() {
    // Utility class.
  }

  static Path defaultInstructionFile(String agent) {
    String normalized = agent == null ? "codex" : agent.toLowerCase(Locale.ROOT);
    return switch (normalized) {
      case "claude" -> Path.of("CLAUDE.md");
      case "gemini" -> Path.of("GEMINI.md");
      case "codex", "github", "copilot" -> Path.of("AGENTS.md");
      default -> throw new IllegalArgumentException("Unsupported instructions agent: " + agent);
    };
  }

  static InstallResult install(Path target, String project, boolean includeMemories)
      throws IOException {
    if (target == null) {
      throw new IllegalArgumentException("--instructions-file resolved to an empty path");
    }
    if (project == null || project.isBlank()) {
      throw new IllegalArgumentException("--project is required");
    }

    String block = managedBlock(renderInstructions(project, includeMemories));
    String existing = Files.exists(target) ? Files.readString(target, StandardCharsets.UTF_8) : "";
    String updated = replaceManagedBlock(existing, block);
    Path parent = target.toAbsolutePath().getParent();
    if (parent != null) {
      Files.createDirectories(parent);
    }
    Files.writeString(target, updated, StandardCharsets.UTF_8);
    return new InstallResult(target, includeMemories);
  }

  private static String replaceManagedBlock(String existing, String block) {
    int start = existing.indexOf(START_MARKER);
    if (start >= 0) {
      int end = existing.indexOf(END_MARKER, start + START_MARKER.length());
      if (end < 0) {
        throw new IllegalStateException("Found incomplete memgraph-ingester instruction markers");
      }
      int afterEnd = skipFollowingLineBreak(existing, end + END_MARKER.length());
      return existing.substring(0, start) + block + existing.substring(afterEnd);
    }

    Matcher legacyMatcher = LEGACY_TEMPLATE_BLOCK.matcher(existing);
    if (legacyMatcher.find()) {
      return replaceLegacyTemplateBlocks(legacyMatcher, block);
    }

    if (existing.isBlank()) {
      return block;
    }
    return existing.stripTrailing() + System.lineSeparator() + System.lineSeparator() + block;
  }

  private static String replaceLegacyTemplateBlocks(Matcher legacyMatcher, String block) {
    StringBuffer updated = new StringBuffer();
    boolean inserted = false;
    do {
      legacyMatcher.appendReplacement(updated, inserted ? "" : Matcher.quoteReplacement(block));
      inserted = true;
    } while (legacyMatcher.find());
    legacyMatcher.appendTail(updated);
    return updated.toString();
  }

  private static int skipFollowingLineBreak(String content, int offset) {
    if (content.startsWith("\r\n", offset)) {
      return offset + 2;
    }
    if (content.startsWith("\n", offset) || content.startsWith("\r", offset)) {
      return offset + 1;
    }
    return offset;
  }

  private static String renderInstructions(String project, boolean includeMemories)
      throws IOException {
    String code = readTemplate(CODE_TEMPLATE).replace(PROJECT_TOKEN, project).stripTrailing();
    if (!includeMemories) {
      return code + System.lineSeparator();
    }
    String memories = readTemplate(MEMORY_TEMPLATE).replace(PROJECT_TOKEN, project).stripTrailing();
    return code
        + System.lineSeparator()
        + System.lineSeparator()
        + memories
        + System.lineSeparator();
  }

  private static String managedBlock(String renderedInstructions) {
    return START_MARKER
        + System.lineSeparator()
        + GENERATED_NOTICE
        + System.lineSeparator()
        + renderedInstructions.stripTrailing()
        + System.lineSeparator()
        + END_MARKER
        + System.lineSeparator();
  }

  private static String readTemplate(String name) throws IOException {
    try (InputStream stream =
        AgentInstructionsInstaller.class.getClassLoader().getResourceAsStream(name)) {
      if (stream == null) {
        throw new IOException("Missing instruction template resource: " + name);
      }
      return new String(stream.readAllBytes(), StandardCharsets.UTF_8);
    }
  }

  record InstallResult(Path target, boolean includeMemories) {
    // Record body intentionally contains no custom members.
  }
}
